# Generated by Django 5.2.4 on 2025-07-09 17:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PageVist",
            new_name="PageVisit",
        ),
    ]
